use std::borrow::Cow;

pub fn localize_cow(text: Cow<'static, str>) -> Cow<'static, str> {
    match zh_cn(text.as_ref()) {
        Some(localized) => Cow::Borrowed(localized),
        None => text,
    }
}

pub fn localize_string(text: String) -> String {
    zh_cn(&text).map(str::to_owned).unwrap_or(text)
}

pub fn localize_str(text: &str) -> Cow<'_, str> {
    match zh_cn(text) {
        Some(localized) => Cow::Borrowed(localized),
        None => Cow::Borrowed(text),
    }
}

fn zh_cn(text: &str) -> Option<&'static str> {
    Some(match text {
        "<NO DESCRIPTION>" => "<无描述>",
        "About Warp" => "关于 Warp",
        "Activate Next Pane" => "激活下一个窗格",
        "Activate Previous Pane" => "激活上一个窗格",
        "Add a description" => "添加描述",
        "Add Cursor Above" => "在上方添加光标",
        "Add Cursor Below" => "在下方添加光标",
        "Add Next Occurrence" => "添加下一个匹配项",
        "AI" => "AI",
        "Apply" => "应用",
        "Appearance" => "外观",
        "Auto-reload settings updated" => "自动续费设置已更新",
        "Back" => "返回",
        "Browse" => "浏览",
        "Bring All to Front" => "全部置于前面",
        "Cancel" => "取消",
        "Cancelled" => "已取消",
        "Choose directory..." => "选择目录...",
        "Choose file..." => "选择文件...",
        "Clear Editor" => "清空编辑器",
        "Close" => "关闭",
        "Close Current Session" => "关闭当前会话",
        "Close Other Tabs" => "关闭其他标签页",
        "Close pane" => "关闭窗格",
        "Close session" => "关闭会话",
        "Close session?" => "关闭会话？",
        "Close Tab" => "关闭标签页",
        "Close Tabs Right" => "关闭右侧标签页",
        "Close Warp AI" => "关闭 Warp AI",
        "Close Window" => "关闭窗口",
        "Command Palette" => "命令面板",
        "Command Search" => "命令搜索",
        "Compact Mode" => "紧凑模式",
        "Configure Keybindings" => "配置快捷键",
        "Connect" => "连接",
        "Copy" => "复制",
        "Copy answer to clipboard" => "复制答案到剪贴板",
        "Copy code to clipboard [Cmd + C]" => "复制代码到剪贴板 [Cmd + C]",
        "Copy link" => "复制链接",
        "Copy on Select within the Terminal" => "在终端中选中即复制",
        "Copy transcript to clipboard" => "复制转录到剪贴板",
        "Create" => "创建",
        "Create and initialize a brand new project" => "创建并初始化一个全新项目",
        "Create anonymous user" => "创建匿名用户",
        "Create new project" => "创建新项目",
        "Cut" => "剪切",
        "Debug" => "调试",
        "Decrease Font Size" => "减小字体",
        "Decrease Zoom" => "缩小",
        "Delete" => "删除",
        "Disable In-band Generators for New Sessions" => "为新会话禁用 In-band Generators",
        "Disable PTY Recording Mode (warp.pty.recording)" => "禁用 PTY 录制模式 (warp.pty.recording)",
        "Disable Shell Debug Mode (-x) for New Sessions" => "为新会话禁用 Shell 调试模式 (-x)",
        "Disable Sync Terminal Inputs" => "禁用终端输入同步",
        "Disable AI features" => "禁用 AI 功能",
        "Disable Warp Drive" => "禁用 Warp Drive",
        "Disable in-band generators for new sessions" => "为新会话禁用 in-band generators",
        "Discard" => "丢弃",
        "Discard changes" => "丢弃更改",
        "Disconnect" => "断开连接",
        "Done" => "完成",
        "Don't show again." => "不再显示。",
        "Drive" => "驱动器",
        "Edit" => "编辑",
        "Enable" => "启用",
        "Enable AI features" => "启用 AI 功能",
        "Enable In-band Generators for New Sessions" => "为新会话启用 In-band Generators",
        "Enable PTY Recording Mode (warp.pty.recording)" => "启用 PTY 录制模式 (warp.pty.recording)",
        "Enable Shell Debug Mode (-x) for New Sessions" => "为新会话启用 Shell 调试模式 (-x)",
        "Enable auto reload?" => "启用自动续费？",
        "Enable servers" => "启用服务器",
        "Enable Warp Drive" => "启用 Warp Drive",
        "Error" => "错误",
        "Error authenticating - please refresh the page" => "认证失败，请刷新页面",
        "Export Default Settings as CSV to home dir" => "将默认设置导出为 CSV 到主目录",
        "Failed to enable auto-reload. Please try updating your settings in Billing & usage." => {
            "启用自动续费失败。请尝试在 Billing & usage 中更新设置。"
        },
        "File" => "文件",
        "Files Palette" => "文件面板",
        "Find" => "查找",
        "Go To Line" => "转到行",
        "Got it" => "知道了",
        "Help" => "帮助",
        "Hide Initialization Block" => "隐藏初始化块",
        "Hide In-band Command Blocks" => "隐藏 In-band 命令块",
        "Hide Warp" => "隐藏 Warp",
        "Hide Warpified SSH Blocks" => "隐藏 Warpified SSH 块",
        "Hide Others" => "隐藏其他",
        "History" => "历史记录",
        "Increase Font Size" => "增大字体",
        "Increase Zoom" => "放大",
        "Install" => "安装",
        "Install servers" => "安装服务器",
        "Installing..." => "正在安装...",
        "Keep editing" => "继续编辑",
        "Launch Configurations" => "启动配置",
        "Launch Config Palette" => "启动配置面板",
        "Learn more" => "了解更多",
        "Loading..." => "加载中...",
        "Log in" => "登录",
        "Log out" => "退出登录",
        "Log out?" => "退出登录？",
        "Manually Toggle Network Status" => "手动切换网络状态",
        "Minimize" => "最小化",
        "Move Tab Left" => "向左移动标签页",
        "Move Tab Right" => "向右移动标签页",
        "Navigation Palette" => "导航面板",
        "New login detected" => "检测到新登录",
        "New Agent Tab" => "新建 Agent 标签页",
        "New File" => "新建文件",
        "New Tab" => "新建标签页",
        "New Terminal Tab" => "新建终端标签页",
        "New Window" => "新建窗口",
        "No" => "否",
        "No images" => "没有图片",
        "No updates available" => "没有可用更新",
        "OK" => "确定",
        "Oops, something went wrong; your team's data could not be found." => {
            "出错了，找不到你团队的数据。"
        },
        "Open an existing local folder or repository" => "打开现有本地文件夹或仓库",
        "Open logs" => "打开日志",
        "Open Recent" => "打开最近项目",
        "Open Repository" => "打开仓库",
        "Open repository" => "打开仓库",
        "Open YAML File" => "打开 YAML 文件",
        "Paste" => "粘贴",
        "Paste your auth token below" => "在下方粘贴你的 auth token",
        "Paste your auth token from the browser to get complete login." => {
            "从浏览器粘贴你的 auth token 以完成登录。"
        },
        "Preferences" => "偏好设置",
        "Privacy Policy..." => "隐私政策...",
        "Quit" => "退出",
        "Redo" => "重做",
        "Refresh" => "刷新",
        "Refer a Friend" => "推荐给朋友",
        "Remove" => "移除",
        "Remove server" => "移除服务器",
        "Rename Tab" => "重命名标签页",
        "Reopen closed session" => "重新打开已关闭会话",
        "Reset Font Size" => "重置字体大小",
        "Reset Zoom" => "重置缩放",
        "Restart" => "重启",
        "Restart all servers" => "重启所有服务器",
        "Restart server" => "重启服务器",
        "Restart Warp AI" => "重启 Warp AI",
        "Save" => "保存",
        "Save as workflow [Cmd + S]" => "另存为工作流 [Cmd + S]",
        "Save changes" => "保存更改",
        "Save Configuration" => "保存配置",
        "Save Current Configuration" => "保存当前配置",
        "Save file" => "保存文件",
        "Save file as..." => "文件另存为...",
        "Save New..." => "保存新配置...",
        "Saving..." => "正在保存...",
        "Select All" => "全选",
        "Send Feedback..." => "发送反馈...",
        "Set Warp as Default Terminal" => "将 Warp 设为默认终端",
        "Settings" => "设置",
        "Sign in" => "登录",
        "Sign in on your browser \nto continue" => "在浏览器中登录\n以继续",
        "Sign in on your browser to continue" => "在浏览器中登录以继续",
        "Skip for now" => "暂时跳过",
        "Show All" => "显示全部",
        "Show Appearance" => "显示外观",
        "Show Initialization Block" => "显示初始化块",
        "Show In-band Command Blocks" => "显示 In-band 命令块",
        "Show Keybindings" => "显示快捷键",
        "Show Settings" => "显示设置",
        "Show Warpified SSH Blocks" => "显示 Warpified SSH 块",
        "Split Pane Down" => "向下拆分窗格",
        "Split Pane Left" => "向左拆分窗格",
        "Split Pane Right" => "向右拆分窗格",
        "Split Pane Up" => "向上拆分窗格",
        "Stop" => "停止",
        "Stop all servers" => "停止所有服务器",
        "Stop server" => "停止服务器",
        "Synchronize Inputs" => "同步输入",
        "Tab" => "标签页",
        "Terminal" => "终端",
        "Toggle Conversation List View" => "切换对话列表视图",
        "Toggle Focus Reporting" => "切换焦点报告",
        "Toggle Full Screen" => "切换全屏",
        "Toggle Global Search" => "切换全局搜索",
        "Toggle Keybindings Page" => "切换快捷键页面",
        "Toggle Maximize Pane" => "切换窗格最大化",
        "Toggle Mouse Reporting" => "切换鼠标报告",
        "Toggle Project Explorer" => "切换项目资源管理器",
        "Toggle Resource Center" => "切换资源中心",
        "Toggle Scroll Reporting" => "切换滚动报告",
        "Toggle Sync All Terminal Inputs In All Tabs" => "同步所有标签页中的终端输入",
        "Toggle Sync Terminal Inputs In Current Tab" => "同步当前标签页中的终端输入",
        "Toggle Warp Drive" => "切换 Warp Drive",
        "Undo" => "撤销",
        "Update available." => "有可用更新。",
        "Use Warp's Prompt" => "使用 Warp 提示符",
        "View" => "视图",
        "View Changelog" => "查看更新日志",
        "Warp Documentation..." => "Warp 文档...",
        "Warp Slack Community..." => "Warp Slack 社区...",
        "Window" => "窗口",
        "Workflows" => "工作流",
        "Yes" => "是",
        "Yes, log out" => "是，退出登录",
        "Yes, skip login" => "是，跳过登录",
        "You are about to close a session that is currently being shared. Closing it will end sharing for everyone." => {
            "你将关闭一个正在共享的会话。关闭后，所有人的共享都会结束。"
        },
        "Zoom" => "缩放",
        _ => return None,
    })
}
