use std::borrow::Cow;

pub fn localize_cow(text: Cow<'static, str>) -> Cow<'static, str> {
    match zh_cn(text.as_ref()) {
        Some(localized) => Cow::Borrowed(localized),
        None => text,
    }
}

pub fn localize_string(text: String) -> String {
    zh_cn(&text).map(str::to_owned).unwrap_or(text)
}

pub fn localize_str(text: &str) -> Cow<'_, str> {
    match zh_cn(text) {
        Some(localized) => Cow::Borrowed(localized),
        None => Cow::Borrowed(text),
    }
}

fn zh_cn(text: &str) -> Option<&'static str> {
    Some(match text {
        "<NO DESCRIPTION>" => "<无描述>",
        "About" => "关于",
        "About Warp" => "关于 Warp",
        "Accept" => "接受",
        "Add" => "添加",
        "Add as context" => "添加为上下文",
        "Add file diff as context" => "将文件差异添加为上下文",
        "Add Profile" => "添加配置",
        "Add repo" => "添加仓库",
        "Add rule" => "添加规则",
        "Add-on credits" => "附加额度",
        "Activate Next Pane" => "激活下一个窗格",
        "Activate Previous Pane" => "激活上一个窗格",
        "Add a description" => "添加描述",
        "Add Cursor Above" => "在上方添加光标",
        "Add Cursor Below" => "在下方添加光标",
        "Add Next Occurrence" => "添加下一个匹配项",
        "Additional metadata" => "附加元数据",
        "again to send to agent" => "再次按下发送给 Agent",
        "again to start new conversation" => "再次按下开始新对话",
        "AI" => "AI",
        "Agent" => "Agent",
        "Agent location" => "Agent 位置",
        "All" => "全部",
        "All locally indexed repos are already selected." => "所有已在本地索引的仓库都已选中。",
        "Allow" => "允许",
        "Always run automatically" => "始终自动运行",
        "Apply" => "应用",
        "Appearance" => "外观",
        "Are you still there?" => "你还在吗？",
        "Artifacts" => "产物",
        "As you or the Agent make changes, you'll be able to track them here." => {
            "当你或 Agent 做出更改时，可以在这里跟踪这些更改。"
        },
        "Ask the Warp agent to assist" => "让 Warp Agent 协助",
        "Ask the Warp agent to resume" => "让 Warp Agent 继续",
        "Attach file" => "附加文件",
        "Auth with GitHub" => "使用 GitHub 授权",
        "Auto reload" => "自动充值",
        "Auto-generate worktree branch name" => "自动生成 worktree 分支名",
        "Auto-reload settings updated" => "自动续费设置已更新",
        "Auto-reload" => "自动充值",
        "Autogenerate worktree branch name" => "自动生成 worktree 分支名",
        "Automatically color tabs based on the directory or repo you're working in." => {
            "根据当前目录或仓库自动为标签页着色。"
        },
        "Automatically create a worktree when opening a new tab" => {
            "打开新标签页时自动创建 worktree"
        },
        "Autonomy settings are configured as part of your team workspace." => {
            "自主性设置由你的团队工作区统一配置。"
        },
        "AWS Access Key ID:" => "AWS Access Key ID：",
        "AWS credentials expired or missing" => "AWS 凭据已过期或缺失",
        "AWS Region:" => "AWS 区域：",
        "Back" => "返回",
        "Background color" => "背景颜色",
        "Balance" => "余额",
        "Beta" => "测试版",
        "Billed to API" => "计入 API 账单",
        "Binary file - no diff available" => "二进制文件，无可用差异",
        "Branch" => "分支",
        "Browse" => "浏览",
        "Bring All to Front" => "全部置于前面",
        "Buy credits" => "购买额度",
        "Call web tools" => "调用网页工具",
        "Cancel" => "取消",
        "Cancelled" => "已取消",
        "Cannot detect diffs for this folder" => "无法检测此文件夹的差异",
        "Change keybinding" => "更改快捷键",
        "changed directory to continue conversation " => "已切换目录以继续对话 ",
        "Changes" => "更改",
        "Character limit exceeded." => "已超出字符限制。",
        "Check out the " => "查看 ",
        "Choose directory..." => "选择目录...",
        "Choose file..." => "选择文件...",
        "Choose an environment" => "选择环境",
        "Choose how you'd like to set up your environment" => "选择环境设置方式",
        "Choose how you’d like to set up your environment:" => "选择你想如何设置环境：",
        "Choose your agent" => "选择你的 Agent",
        "Clear Editor" => "清空编辑器",
        "Clear all" => "全部清除",
        "Clear filters" => "清除筛选",
        "Close" => "关闭",
        "Close Current Session" => "关闭当前会话",
        "Close Other Tabs" => "关闭其他标签页",
        "Close pane" => "关闭窗格",
        "Close session" => "关闭会话",
        "Close session?" => "关闭会话？",
        "Close Tab" => "关闭标签页",
        "Close Tabs Right" => "关闭右侧标签页",
        "Close Warp AI" => "关闭 Warp AI",
        "Close Window" => "关闭窗口",
        "Cloud Agent Run Cancelled" => "云端 Agent 运行已取消",
        "Cloud agents require an environment that they'll run in to get their task done. Create your first environment below. You'll be able to edit the environment later, or add new environments when you need them." => {
            "云端 Agent 需要一个运行环境来完成任务。请在下方创建第一个环境。之后你可以编辑该环境，也可以按需添加新环境。"
        },
        "Code review" => "代码审查",
        "Code symbols indexing..." => "正在索引代码符号...",
        "Collapse" => "折叠",
        "Code" => "代码",
        "Command Palette" => "命令面板",
        "Command edited." => "命令已编辑。",
        "Command Search" => "命令搜索",
        "Comment" => "评论",
        "Comment imported from GitHub" => "从 GitHub 导入的评论",
        "Compact Mode" => "紧凑模式",
        "Commit" => "提交",
        "Commit and create PR" => "提交并创建 PR",
        "Commit message" => "提交信息",
        "Configure Keybindings" => "配置快捷键",
        "Configure" => "配置",
        "Configure access on GitHub" => "在 GitHub 上配置访问权限",
        "Connect" => "连接",
        "Connect SuperGrok subscription" => "连接 SuperGrok 订阅",
        "Connect your SuperGrok subscription to use Grok models in the Warp Agent through your xAI account." => {
            "连接你的 SuperGrok 订阅，通过 xAI 账号在 Warp Agent 中使用 Grok 模型。"
        },
        "Context window" => "上下文窗口",
        "Context window usage" => "上下文窗口用量",
        "Continue" => "继续",
        "Continue locally" => "在本地继续",
        "Continue this cloud conversation" => "继续此云端对话",
        "Copy" => "复制",
        "Copy answer to clipboard" => "复制答案到剪贴板",
        "Copy code to clipboard [Cmd + C]" => "复制代码到剪贴板 [Cmd + C]",
        "Copy file path" => "复制文件路径",
        "Copy link" => "复制链接",
        "Copy on Select within the Terminal" => "在终端中选中即复制",
        "Copy transcript to clipboard" => "复制转录到剪贴板",
        "couldn't find original conversation directory " => "找不到原始对话目录 ",
        "Create a key to manage external access to Warp" => "创建密钥以管理对 Warp 的外部访问",
        "Create an environment" => "创建环境",
        "Create an integration" => "创建集成",
        "Create environment" => "创建环境",
        "Create your first tab config" => "创建你的第一个标签页配置",
        "Create" => "创建",
        "Create and initialize a brand new project" => "创建并初始化一个全新项目",
        "Create anonymous user" => "创建匿名用户",
        "Create new project" => "创建新项目",
        "Cut" => "剪切",
        "Custom endpoints" => "自定义端点",
        "Customizable in appearance settings." => "可在外观设置中自定义。",
        "cycle past commands and conversations" => "循环浏览历史命令和对话",
        "Cycle suggestions" => "切换建议",
        "Debug" => "调试",
        "Debug output" => "调试输出",
        "Decrease Font Size" => "减小字体",
        "Decrease Zoom" => "缩小",
        "Delete" => "删除",
        "Delete environment" => "删除环境",
        "Delete MCP" => "删除 MCP",
        "Delete profile" => "删除配置",
        "Delete rule" => "删除规则",
        "Density" => "密度",
        "Description" => "描述",
        "Disable In-band Generators for New Sessions" => "为新会话禁用 In-band Generators",
        "Disable PTY Recording Mode (warp.pty.recording)" => "禁用 PTY 录制模式 (warp.pty.recording)",
        "Disable Shell Debug Mode (-x) for New Sessions" => "为新会话禁用 Shell 调试模式 (-x)",
        "Disable Sync Terminal Inputs" => "禁用终端输入同步",
        "Disable AI features" => "禁用 AI 功能",
        "Disable Warp Drive" => "禁用 Warp Drive",
        "Disable Warp Agent" => "禁用 Warp Agent",
        "Disabled by your administrator" => "已被管理员禁用",
        "Disable in-band generators for new sessions" => "为新会话禁用 in-band generators",
        "Discard" => "丢弃",
        "Discard changes" => "丢弃更改",
        "Disconnect" => "断开连接",
        "Dismiss" => "关闭",
        "Don't Save" => "不保存",
        "Don't ask me this again" => "不再询问",
        "Don't show again" => "不再显示",
        "Done" => "完成",
        "Don't show again." => "不再显示。",
        "Drive" => "驱动器",
        "Edit" => "编辑",
        "Edit Profile" => "编辑配置",
        "Edit rule" => "编辑规则",
        "Edit Variables" => "编辑变量",
        "Editor and Projects" => "编辑器和项目",
        "Enable" => "启用",
        "Enable AI features" => "启用 AI 功能",
        "Enable In-band Generators for New Sessions" => "为新会话启用 In-band Generators",
        "Enable PTY Recording Mode (warp.pty.recording)" => "启用 PTY 录制模式 (warp.pty.recording)",
        "Enable Shell Debug Mode (-x) for New Sessions" => "为新会话启用 Shell 调试模式 (-x)",
        "Enable auto reload?" => "启用自动续费？",
        "Enable notifications" => "启用通知",
        "Enable servers" => "启用服务器",
        "Enable Warp shell integration in this session" => "在此会话中启用 Warp shell 集成",
        "Enable Warp Drive" => "启用 Warp Drive",
        "Enables codebase indexing and WARP.md" => "启用代码库索引和 WARP.md",
        "Enter custom Docker image name:" => "输入自定义 Docker 镜像名称：",
        "Error" => "错误",
        "Error authenticating - please refresh the page" => "认证失败，请刷新页面",
        "Export Default Settings as CSV to home dir" => "将默认设置导出为 CSV 到主目录",
        "Failed to enable auto-reload. Please try updating your settings in Billing & usage." => {
            "启用自动续费失败。请尝试在 Billing & usage 中更新设置。"
        },
        "File" => "文件",
        "File explorer" => "文件资源管理器",
        "File renamed without changes" => "文件已重命名，无内容更改",
        "Files Palette" => "文件面板",
        "Find" => "查找",
        "Finish" => "完成",
        "Fork this conversation locally" => "在本地 fork 此对话",
        "Free credits" => "免费额度",
        "for code review" => "进行代码审查",
        "for terminal" => "用于终端",
        "Go To Line" => "转到行",
        "Got it" => "知道了",
        "Get started" => "开始使用",
        "Get Warping" => "开始使用 Warp",
        "Give control back to agent" => "将控制权交还给 Agent",
        "Global Search" => "全局搜索",
        "Help" => "帮助",
        "Hide Initialization Block" => "隐藏初始化块",
        "Hide In-band Command Blocks" => "隐藏 In-band 命令块",
        "Hide Warp" => "隐藏 Warp",
        "Hide Warpified SSH Blocks" => "隐藏 Warpified SSH 块",
        "Hide Others" => "隐藏其他",
        "History" => "历史记录",
        "Index new folder" => "索引新文件夹",
        "Increase Font Size" => "增大字体",
        "Increase Zoom" => "放大",
        "Initialize codebase" => "初始化代码库",
        "Initialize Project" => "初始化项目",
        "Install" => "安装",
        "Install nvm" => "安装 nvm",
        "Install servers" => "安装服务器",
        "Installing..." => "正在安装...",
        "Keep editing" => "继续编辑",
        "Keybindings" => "快捷键",
        "Keyboard shortcuts" => "快捷键",
        "Kick off an agent task to view usage history here." => "启动一个 Agent 任务后，可在这里查看用量历史。",
        "Launch Configurations" => "启动配置",
        "Launch Config Palette" => "启动配置面板",
        "Last 30 days" => "最近 30 天",
        "Learn more" => "了解更多",
        "Load more" => "加载更多",
        "Loading..." => "加载中...",
        "Loading session..." => "正在加载会话...",
        "Log in" => "登录",
        "Log out" => "退出登录",
        "Log out?" => "退出登录？",
        "Manually Toggle Network Status" => "手动切换网络状态",
        "Manage" => "管理",
        "Manage defaults" => "管理默认值",
        "Manage rules" => "管理规则",
        "Mark all as read" => "全部标记为已读",
        "Minimize" => "最小化",
        "Name" => "名称",
        "Move Tab Left" => "向左移动标签页",
        "Move Tab Right" => "向右移动标签页",
        "Navigation Palette" => "导航面板",
        "Navigate to a repo and initialize it for coding" => "进入一个仓库并初始化以进行编码",
        "New" => "新建",
        "New agent" => "新建 Agent",
        "New login detected" => "检测到新登录",
        "New Agent Tab" => "新建 Agent 标签页",
        "New conversation" => "新建对话",
        "New environment" => "新建环境",
        "New File" => "新建文件",
        "New Tab" => "新建标签页",
        "New Terminal Tab" => "新建终端标签页",
        "New Window" => "新建窗口",
        "Next" => "下一步",
        "No" => "否",
        "No code to be restored" => "没有可恢复的代码",
        "No conversations yet" => "暂无对话",
        "No images" => "没有图片",
        "No open changes" => "没有打开的更改",
        "No results found" => "未找到结果",
        "No tabs open" => "没有打开的标签页",
        "No updates available" => "没有可用更新",
        "No usage history" => "暂无用量历史",
        "Notifications setup instructions" => "通知设置说明",
        "OK" => "确定",
        "Oops, something went wrong; your team's data could not be found." => {
            "出错了，找不到你团队的数据。"
        },
        "Open an existing local folder or repository" => "打开现有本地文件夹或仓库",
        "Open all in code review" => "在代码审查中打开全部",
        "Open in code review" => "在代码审查中打开",
        "Open in Warp" => "在 Warp 中打开",
        "Open logs" => "打开日志",
        "Open plan" => "打开计划",
        "Open Recent" => "打开最近项目",
        "Open Repository" => "打开仓库",
        "Open repository" => "打开仓库",
        "Open settings file" => "打开设置文件",
        "Open Tab" => "打开标签页",
        "Open YAML File" => "打开 YAML 文件",
        "Oz Cloud API Keys" => "Oz Cloud API 密钥",
        "Paste" => "粘贴",
        "Paste your auth token below" => "在下方粘贴你的 auth token",
        "Paste your auth token from the browser to get complete login." => {
            "从浏览器粘贴你的 auth token 以完成登录。"
        },
        "Preferences" => "偏好设置",
        "Personal" => "个人",
        "Plan" => "计划",
        "Plugin update instructions" => "插件更新说明",
        "Previous" => "上一步",
        "Privacy Policy..." => "隐私政策...",
        "Purchased this month" => "本月已购买",
        "Quit" => "退出",
        "Redo" => "重做",
        "Refine" => "优化",
        "Refresh" => "刷新",
        "Refresh AWS Credentials" => "刷新 AWS 凭据",
        "Refer a Friend" => "推荐给朋友",
        "Reject" => "拒绝",
        "Remove" => "移除",
        "Remove endpoint" => "移除端点",
        "Remove from team" => "从团队中移除",
        "Remove queued prompt" => "移除排队提示",
        "Remove server" => "移除服务器",
        "Rename Tab" => "重命名标签页",
        "Replace all" => "全部替换",
        "Reopen closed session" => "重新打开已关闭会话",
        "Reset Font Size" => "重置字体大小",
        "Reset Zoom" => "重置缩放",
        "Restart" => "重启",
        "Restart all servers" => "重启所有服务器",
        "Restart server" => "重启服务器",
        "Restart Warp AI" => "重启 Warp AI",
        "Restore" => "恢复",
        "Review changes" => "审查更改",
        "Rewind" => "回退",
        "Rich Input" => "富文本输入",
        "Run" => "运行",
        "Runs" => "运行记录",
        "Save" => "保存",
        "Save as workflow [Cmd + S]" => "另存为工作流 [Cmd + S]",
        "Save changes" => "保存更改",
        "Save Configuration" => "保存配置",
        "Save Current Configuration" => "保存当前配置",
        "Save file" => "保存文件",
        "Save file as..." => "文件另存为...",
        "Save New..." => "保存新配置...",
        "Saving..." => "正在保存...",
        "Search" => "搜索",
        "See what's new" => "查看新功能",
        "Select All" => "全选",
        "Select all" => "全选",
        "Send Feedback..." => "发送反馈...",
        "Send now" => "立即发送",
        "Set Warp as Default Terminal" => "将 Warp 设为默认终端",
        "Settings" => "设置",
        "Share with team" => "与团队共享",
        "Sign in" => "登录",
        "Sign in on your browser \nto continue" => "在浏览器中登录\n以继续",
        "Sign in on your browser to continue" => "在浏览器中登录以继续",
        "Skip for now" => "暂时跳过",
        "Show All" => "显示全部",
        "Show Appearance" => "显示外观",
        "Show Initialization Block" => "显示初始化块",
        "Show initialization block" => "显示初始化块",
        "Show In-band Command Blocks" => "显示 In-band 命令块",
        "Show Keybindings" => "显示快捷键",
        "Show running processes" => "显示正在运行的进程",
        "Show Settings" => "显示设置",
        "Show Warpified SSH Blocks" => "显示 Warpified SSH 块",
        "Skip all" => "全部跳过",
        "Split Pane Down" => "向下拆分窗格",
        "Split Pane Left" => "向左拆分窗格",
        "Split Pane Right" => "向右拆分窗格",
        "Split Pane Up" => "向上拆分窗格",
        "Stop" => "停止",
        "Stop all servers" => "停止所有服务器",
        "Stop server" => "停止服务器",
        "Stop sharing" => "停止共享",
        "Suggested" => "推荐",
        "Synchronize Inputs" => "同步输入",
        "Tab" => "标签页",
        "Take control" => "接管控制",
        "Take over" => "接管",
        "Terminal" => "终端",
        "Theme name" => "主题名称",
        " to cycle tabs" => " 切换标签",
        " to dismiss" => " 关闭",
        " to execute" => " 执行",
        " to navigate" => " 导航",
        " to override" => " 覆盖",
        " to remove" => " 移除",
        " to select" => " 选择",
        " to send" => " 发送",
        " to continue conversation" => " 继续对话",
        " to learn more." => " 了解更多。",
        " · Check now" => " · 立即检查",
        " (autodetected) " => "（自动检测）",
        " + Add new repo" => " + 添加新仓库",
        " change repos" => " 更改仓库",
        " current pane" => " 当前窗格",
        " new /agent conversation" => " 新建 /agent 对话",
        " new conversation" => " 新建对话",
        " new pane" => " 新建窗格",
        " open plan" => " 打开计划",
        " or " => " 或 ",
        " plan with agent" => " 使用 Agent 规划",
        " select and save to profile" => " 选择并保存到配置",
        "+ Add custom model" => "+ 添加自定义模型",
        "1 Comment" => "1 条评论",
        "autodetected shell command, " => "自动检测为 shell 命令，",
        "Directory tab colors" => "目录标签页颜色",
        "Environment details" => "环境详情",
        "Environment setup commands" => "环境设置命令",
        "Error loading diffs" => "加载差异失败",
        "Example queries" => "示例查询",
        "Expiration" => "过期时间",
        "Failed to start environment" => "启动环境失败",
        "First, set up an environment to create an integration." => {
            "请先设置环境，然后创建集成。"
        },
        "Fork current conversation" => "Fork 当前对话",
        "From GitHub" => "来自 GitHub",
        "Getting started with Oz cloud agents" => "开始使用 Oz 云端 Agent",
        "GitHub Authentication Required" => "需要 GitHub 认证",
        "go back to terminal" => "返回终端",
        "Go to line" => "转到行",
        "Grace period (seconds)" => "宽限时间（秒）",
        "Harness" => "Harness",
        "Height %" => "高度 %",
        "I'm looking for..." => "我想查找...",
        "Import" => "导入",
        "Include unstaged" => "包含未暂存内容",
        "Included commits" => "包含的提交",
        "Install nvm to enable version switching" => "安装 nvm 以启用版本切换",
        "Installed" => "已安装",
        "Introducing universal agent support: level up any coding agent with Warp" => {
            "推出通用 Agent 支持：用 Warp 增强任何编码 Agent"
        },
        "Invalid regex" => "无效正则表达式",
        "Keybinding" => "快捷键",
        "Loading agents..." => "正在加载 Agent...",
        "Loading prompt..." => "正在加载提示...",
        "Loading results..." => "正在加载结果...",
        "Manual setup: Create a Slack or Linear integration with the Oz CLI" => {
            "手动设置：使用 Oz CLI 创建 Slack 或 Linear 集成"
        },
        "Meet your new agent inbox" => "认识你的新 Agent 收件箱",
        "Missing a repo?" => "缺少仓库？",
        "Monthly overage spending limit" => "每月超额支出上限",
        "Name (optional)" => "名称（可选）",
        "New empty file" => "新建空文件",
        "New terminal session" => "新建终端会话",
        "New worktree" => "新建 worktree",
        "next" => "下一个",
        "No agents available. Create one first." => "没有可用 Agent。请先创建一个。",
        "No API Keys" => "没有 API 密钥",
        "No API keys match your search" => "没有符合搜索条件的 API 密钥",
        "No cloud environment was started" => "未启动云端环境",
        "No environments match your search." => "没有符合搜索条件的环境。",
        "No file selected" => "未选择文件",
        "No files to discard" => "没有可丢弃的文件",
        "No matches" => "无匹配项",
        "No matching conversations" => "没有匹配的对话",
        "No MCP server selected" => "未选择 MCP 服务器",
        "No node versions installed" => "未安装 Node.js 版本",
        "No repos selected yet" => "尚未选择仓库",
        "No repositories found" => "未找到仓库",
        "No results matched your filters" => "没有符合筛选条件的结果",
        "No secrets found. Save to use this value directly or click the key to add a secret." => {
            "未找到密钥。保存后可直接使用此值，或点击钥匙图标添加密钥。"
        },
        "No settings match your search." => "没有匹配的设置。",
        "No skills found" => "未找到技能",
        "No tabs match your search." => "没有匹配的标签页。",
        "No tools available" => "没有可用工具",
        "No URLs fetched" => "未获取 URL",
        "No URLs found" => "未找到 URL",
        "None" => "无",
        "Note that AI credits made near your chosen limit may exceed it by a few dollars." => {
            "请注意，接近所选上限时产生的 AI 额度费用可能会略微超出几美元。"
        },
        "Now using Full Terminal Agent's default model." => {
            "当前使用 Full Terminal Agent 的默认模型。"
        },
        "open code review" => "打开代码审查",
        "open conversation" => "打开对话",
        "OpenAI base URL (optional, press Enter to skip):" => {
            "OpenAI base URL（可选，按 Enter 跳过）："
        },
        "Or" => "或",
        "Or, supply your own existing docker image." => "或者提供你已有的 Docker 镜像。",
        "Orchestrate any agent, anywhere" => "随时随地编排任何 Agent",
        "Other team members' usage across add-on, pay-as-you-go, and cloud-only credits." => {
            "其他团队成员在附加额度、按量付费和纯云端额度中的用量。"
        },
        "Outdated" => "已过期",
        "Pane title as" => "窗格标题显示为",
        "Plan auto-sync" => "计划自动同步",
        "Please authenticate with GitHub to continue" => "请使用 GitHub 认证以继续",
        "Press new keyboard shortcut" => "按下新的快捷键",
        "prev" => "上一个",
        "Project explorer unavailable" => "项目资源管理器不可用",
        "Project Explorer" => "项目资源管理器",
        "Project Skill" => "项目技能",
        "Provide your endpoint details below. You can add as many models from the endpoint as you'd like and can also provide aliases for the model picker in your input." => {
            "在下方提供端点详情。你可以从该端点添加任意数量的模型，也可以为输入框中的模型选择器提供别名。"
        },
        "Provided API key is not valid" => "提供的 API 密钥无效",
        "Queued" => "已排队",
        "Quick start: Visit oz.warp.dev for a UI-based setup experience." => {
            "快速开始：访问 oz.warp.dev 通过界面完成设置。"
        },
        "RECENT ACTIVITY" => "最近活动",
        "Recommended" => "推荐",
        "References" => "引用",
        "Regex pattern" => "正则表达式",
        "Remote host disconnected. You will not be able to see updates and save changes." => {
            "远程主机已断开连接。你将无法看到更新或保存更改。"
        },
        "Repo(s)" => "仓库",
        "Retry" => "重试",
        "rewind" => "回退",
        "Rewinding does not affect files edited manually or via shell commands." => {
            "回退不会影响手动编辑或通过 shell 命令编辑的文件。"
        },
        "Run your agent task in an isolated cloud environment." => {
            "在隔离的云端环境中运行你的 Agent 任务。"
        },
        "Search sessions, agents, files..." => "搜索会话、Agent、文件...",
        "seconds" => "秒",
        "seconds to complete" => "秒后完成",
        "Select a git repository to enable worktree support" => {
            "选择一个 Git 仓库以启用 worktree 支持"
        },
        "Select directory" => "选择目录",
        "selected text attached as context" => "已将选中文本附加为上下文",
        "Session type" => "会话类型",
        "Set by Team Workspace" => "由团队工作区设置",
        "Set up a reusable starting point for your tabs. Pick a repo, choose a session type, and optionally attach a worktree. Use it whenever you want to open a tab with this setup." => {
            "为标签页设置可复用的起点。选择仓库、会话类型，并可选择附加 worktree。之后可随时用这套设置打开标签页。"
        },
        "Show" => "显示",
        "Some settings will take effect when you open a new session." => {
            "部分设置将在打开新会话后生效。"
        },
        "Staging IAP credentials" => "Staging IAP 凭据",
        "Start a new Oz cloud agent" => "启动新的 Oz 云端 Agent",
        "Start Oz cloud agents directly in Warp from an integration (Linear, Slack), with an event (GitHub, built-in schedule), or programmatically with the Oz SDK or CLI." => {
            "可通过集成（Linear、Slack）、事件（GitHub、内置计划）或使用 Oz SDK/CLI 编程方式，直接在 Warp 中启动 Oz 云端 Agent。"
        },
        "start a new agent conversation" => "开始新的 Agent 对话",
        "start a new cloud agent conversation" => "开始新的云端 Agent 对话",
        "State-of-the-art models require paid plans." => "先进模型需要付费计划。",
        "Status" => "状态",
        "Subscribe" => "订阅",
        "Suggestions:" => "建议：",
        "Switch back to horizontal tabs" => "切回水平标签页",
        "switch model" => "切换模型",
        "Sync light/dark theme with OS" => "跟随系统切换浅色/深色主题",
        "Tab item" => "标签项",
        "Tasks" => "任务",
        "The agent may use web search when helpful for completing tasks." => {
            "Agent 可在有助于完成任务时使用网页搜索。"
        },
        "The AWS CLI is required to authenticate with your organization's AWS Bedrock. Install it to continue." => {
            "需要 AWS CLI 才能认证你组织的 AWS Bedrock。请安装后继续。"
        },
        "The base model's working memory — how many tokens of your conversation, code, and documents it can consider at once. Larger windows enable longer conversations and more coherent responses over bigger codebases, at the cost of higher latency and compute usage." => {
            "基础模型的工作记忆，也就是它一次可考虑的对话、代码和文档 token 数。更大的窗口支持更长对话和更大代码库上的连贯响应，但会增加延迟和计算用量。"
        },
        "The output from Warp's initialization script is visible above to assist with debugging." => {
            "上方显示了 Warp 初始化脚本的输出，可用于辅助调试。"
        },
        "The plans this agent creates will be automatically added and synced to Warp Drive." => {
            "此 Agent 创建的计划会自动添加并同步到 Warp Drive。"
        },
        "Thinking..." => "思考中...",
        "This file has saved changes that are not reflected here." => {
            "此文件有已保存但尚未反映在此处的更改。"
        },
        "This is an automated agent on your team." => "这是你团队中的自动化 Agent。",
        "This menu helps you switch between Node.js versions — but it requires nvm to be installed." => {
            "此菜单可帮助你切换 Node.js 版本，但需要先安装 nvm。"
        },
        "This secret key is shown only once. Copy and store it securely." => {
            "此密钥只显示一次。请复制并安全保存。"
        },
        "This suggestion is being edited in another tab." => "此建议正在另一个标签页中编辑。",
        "to cycle parameters" => "切换参数",
        "to exit shell mode" => "退出 shell 模式",
        "to fork and continue" => "fork 并继续",
        "to hide help" => "隐藏帮助",
        "to index this codebase and generate an AGENTS.md for optimal performance" => {
            "索引此代码库并生成 AGENTS.md，以获得最佳效果"
        },
        "to resume conversation" => "继续对话",
        "To use AI features, please create an account." => "要使用 AI 功能，请创建账号。",
        "To use Warp Drive, please create an account." => "要使用 Warp Drive，请创建账号。",
        "Toast notifications stay visible for" => "Toast 通知保持可见",
        "Total overages" => "超额总计",
        "Tools Panel" => "工具面板",
        "Tools panel" => "工具面板",
        "Try installing versions with nvm" => "尝试使用 nvm 安装版本",
        "Try it out" => "试试看",
        "Type" => "类型",
        "Toggle Conversation List View" => "切换对话列表视图",
        "Toggle Focus Reporting" => "切换焦点报告",
        "Toggle Full Screen" => "切换全屏",
        "Toggle Global Search" => "切换全局搜索",
        "Toggle Hide CLI Responses" => "切换隐藏 CLI 响应",
        "Toggle Keybindings Page" => "切换快捷键页面",
        "Toggle Maximize Pane" => "切换窗格最大化",
        "Toggle Mouse Reporting" => "切换鼠标报告",
        "Toggle Project Explorer" => "切换项目资源管理器",
        "Toggle Resource Center" => "切换资源中心",
        "Toggle Scroll Reporting" => "切换滚动报告",
        "Toggle Sync All Terminal Inputs In All Tabs" => "同步所有标签页中的终端输入",
        "Toggle Sync Terminal Inputs In Current Tab" => "同步当前标签页中的终端输入",
        "Toggle Warp Drive" => "切换 Warp Drive",
        "Undo" => "撤销",
        "Update" => "更新",
        "Update Agent" => "更新 Agent",
        "Update available." => "有可用更新。",
        "Update Warp plugin" => "更新 Warp 插件",
        "Use agent" => "使用 Agent",
        "Use latest codex model" => "使用最新 Codex 模型",
        "Use Warp's Prompt" => "使用 Warp 提示符",
        "View" => "视图",
        "View Agents" => "查看 Agent",
        "View all cloud runs" => "查看所有云端运行",
        "View Changelog" => "查看更新日志",
        "View in Oz" => "在 Oz 中查看",
        "Visit Oz" => "访问 Oz",
        "Visit the repo" => "访问仓库",
        "Voice input" => "语音输入",
        "Warp Documentation..." => "Warp 文档...",
        "Warp is now open-source" => "Warp 现已开源",
        "Warp Slack Community..." => "Warp Slack 社区...",
        "Warpify subshell" => "Warpify 子 shell",
        "Window" => "窗口",
        "Workflows" => "工作流",
        "Yes" => "是",
        "Yes, log out" => "是，退出登录",
        "Yes, skip login" => "是，跳过登录",
        "You are about to close a session that is currently being shared. Closing it will end sharing for everyone." => {
            "你将关闭一个正在共享的会话。关闭后，所有人的共享都会结束。"
        },
        "/agent for new conversation" => "/agent 新建对话",
        "alias name" => "别名名称",
        "Auth Token" => "认证令牌",
        "command (supports regex)" => "命令（支持正则）",
        "Commands, comma separated" => "命令，用逗号分隔",
        "default" => "默认",
        "Directory path" => "目录路径",
        "e.g. \"Google API Key\"" => "例如 \"Google API Key\"",
        "e.g. \"YOLO code\"" => "例如 \"YOLO code\"",
        "e.g. ~/code-repos/repo" => "例如 ~/code-repos/repo",
        "e.g. ls .*" => "例如 ls .*",
        "e.g. rm .*" => "例如 rm .*",
        "e.g., GLM-5" => "例如 GLM-5",
        "e.g., GLM-5-FP8" => "例如 GLM-5-FP8",
        "e.g., sk-..." => "例如 sk-...",
        "e.g., Zach's external models" => "例如 Zach 的外部模型",
        "Enter auth token" => "输入认证令牌",
        "Executable path" => "可执行文件路径",
        "host (supports regex)" => "主机（支持正则）",
        "Line number:Column" => "行号:列号",
        "Link (web or file)" => "链接（网页或文件）",
        "Please include 'https://'" => "请包含 'https://'",
        "Search API keys" => "搜索 API key",
        "Search diff sets or branches to compare…" => "搜索要比较的 diff set 或分支…",
        "Search in files" => "在文件中搜索",
        "Search MCP Servers" => "搜索 MCP 服务器",
        "Search repos" => "搜索仓库",
        "Search secrets or create a new one" => "搜索密钥或创建新密钥",
        "Search tabs..." => "搜索标签页...",
        "Text" => "文本",
        "Type owner/repo and press Enter to add, or select from dropdown." => {
            "输入 owner/repo 并按 Enter 添加，或从下拉列表中选择。"
        },
        "Type your answer and press Enter" => "输入你的回答并按 Enter",
        "Unable to load file content" => "无法加载文件内容",
        "Uniform padding (px)" => "统一内边距 (px)",
        "Untitled" => "未命名",
        "Upgrade for access to premium models." => "升级后可使用高级模型。",
        "Usage" => "用量",
        "Version" => "版本",
        "View as" => "查看方式",
        "View changelog" => "查看更新日志",
        "View details" => "查看详情",
        "Warp will prevent use of premium models when this dollar limit is reached. Resets on a monthly basis." => {
            "达到此美元限额后，Warp 将阻止使用高级模型。每月重置。"
        },
        "We've made major improvements to Warp's cloud agent orchestration platform, Oz." => {
            "我们对 Warp 的云端 Agent 编排平台 Oz 做了重大改进。"
        },
        "When a command takes longer than" => "当命令运行超过",
        "Width %" => "宽度 %",
        "Window positions won't be restored on Wayland. " => "在 Wayland 上不会恢复窗口位置。 ",
        "You haven’t set up any environments yet." => "你还没有设置任何环境。",
        "You may want to try using different keywords or checking for any possible typos." => {
            "可以尝试使用不同关键词，或检查是否有拼写错误。"
        },
        "You, our community, can participate in building Warp using an agent-first workflow." => {
            "你和社区可以使用 Agent 优先的工作流参与构建 Warp。"
        },
        "You're viewing a snapshot" => "你正在查看快照",
        "Your credentials are encrypted end-to-end. " => "你的凭据已端到端加密。 ",
        "Your new team name" => "你的新团队名称",
        "Your organization disallows AI when the active pane contains content from a remote session" => {
            "当活动窗格包含远程会话内容时，你的组织禁止使用 AI"
        },
        "Your profile is set to always ask for permission to execute commands." => {
            "你的配置已设为执行命令前始终请求权限。"
        },
        "Your Warp admin has enabled AWS Bedrock for your team." => {
            "你的 Warp 管理员已为团队启用 AWS Bedrock。"
        },
        " Ask a question..." => " 提一个问题...",
        " Type a response or click one above..." => " 输入回复，或点击上方选项...",
        "# Enter a shell command that generates variants, delimited by newlines.\n\ngit branch -a" => {
            "# 输入用于生成变量的 shell 命令，每行一个。\n\ngit branch -a"
        },
        "+ Add directory…" => "+ 添加目录…",
        "+ Add new repo..." => "+ 添加新仓库...",
        "Access your tab configs here." => "在这里访问你的标签页配置。",
        "Add directory color" => "添加目录颜色",
        "Agent harness" => "Agent 执行环境",
        "API key" => "API key",
        "Attach context" => "附加上下文",
        "Auto-approve all agent actions for this task" => "自动批准此任务的所有 Agent 操作",
        "Auto-reload is enabled" => "已启用自动充值",
        "Automatically generate a theme based on extracted colors from an image (.png, .jpg)." => {
            "根据图片（.png、.jpg）中提取的颜色自动生成主题。"
        },
        "Break this work into coordinated streams with multiple agents." => {
            "用多个 Agent 将此工作拆分为协同流程。"
        },
        "Choose agent model" => "选择 Agent 模型",
        "Choose an agent model" => "选择 Agent 模型",
        "Choose an AI execution profile" => "选择 AI 执行配置",
        "Cloud agent trial" => "云端 Agent 试用",
        "Command" => "命令",
        "Couldn't connect to the Warp SSH extension" => "无法连接 Warp SSH 扩展",
        "e.g. Never use unwrap in Rust" => "例如 Never use unwrap in Rust",
        "e.g. Rust rules" => "例如 Rust 规则",
        "e.g., this environment is for all front end focused agents" => {
            "例如，此环境用于所有专注前端的 Agent"
        },
        "Enter your prompt here... (e.g., 'Create a function to sort an array of objects by date' or 'Help me debug this React component')." => {
            "在这里输入提示...（例如：'Create a function to sort an array of objects by date' 或 'Help me debug this React component'）。"
        },
        "Environments" => "环境",
        "Execution host" => "执行主机",
        "Filter block output" => "筛选块输出",
        "If you take edit controls, the current editor will be forced into view mode" => {
            "如果你接管编辑控制权，当前编辑器将被强制切换为查看模式"
        },
        "If you want to create an environment with repos, rerun this command and pass in file paths or GitHub links as arguments, e.g. \"/create-environment <filepath> <GitHub URL>\"." => {
            "如果想创建包含仓库的环境，请重新运行此命令，并将文件路径或 GitHub 链接作为参数传入，例如 \"/create-environment <filepath> <GitHub URL>\"。"
        },
        "Inherit key from environment" => "从环境继承密钥",
        "Iterate with agent" => "用 Agent 迭代",
        "Kick off a cloud agent" => "启动云端 Agent",
        "Look incorrect? " => "看起来不对？ ",
        "Looking for settings to import..." => "正在查找可导入的设置...",
        "Name can only contain letters, numbers, hyphens, and underscores" => {
            "名称只能包含字母、数字、连字符和下划线"
        },
        "Next, let’s set up your prompt. Warp has a custom prompt builder or you can select PS1 to honor your pre-existing prompt configuration." => {
            "接下来设置提示符。Warp 提供自定义提示符构建器，也可以选择 PS1 以沿用现有提示符配置。"
        },
        "No existing prompt." => "没有现有提示符。",
        "Replace" => "替换",
        "Run metadata is not available" => "运行元数据不可用",
        "Search by name or by keys (ex. \"cmd d\")" => "按名称或按键搜索（例如 \"cmd d\"）",
        "Search models" => "搜索模型",
        "Search rules" => "搜索规则",
        "Select a settings profile to import:" => "选择要导入的设置配置：",
        "Sharing in Warp Drive" => "在 Warp Drive 中共享",
        "Start remote control" => "启动远程控制",
        "The primary model all agents will use." => "所有 Agent 将使用的主模型。",
        "This will permanently delete the theme." => "这将永久删除该主题。",
        "Title (optional)" => "标题（可选）",
        "Type '#' for AI command suggestions" => "输入 '#' 查看 AI 命令建议",
        "Type a commit message" => "输入提交信息",
        "Unlock smarter, more consistent responses by letting the Agent understand your codebase and generate rules for it. You can also do this at any point by running /init" => {
            "让 Agent 理解你的代码库并为其生成规则，可获得更智能、更一致的回复。你也可以随时运行 /init 完成此操作"
        },
        "Update Warp" => "更新 Warp",
        "Usage reporting is currently limited" => "用量报告当前受限",
        "Use orchestration" => "使用编排",
        "Variant" => "变量值",
        "View all" => "查看全部",
        "Warp prompt" => "Warp 提示符",
        "We may collect certain console interactions to improve Warp's AI capabilities. You can opt out any time." => {
            "我们可能会收集某些控制台交互，以改进 Warp 的 AI 能力。你可以随时选择退出。"
        },
        "Welcome to Warp!" => "欢迎使用 Warp！",
        "What's new in Oz" => "Oz 的新增内容",
        "You are offline. Some files will be read only." => "你已离线。部分文件将为只读。",
        "You can view this shared session, but run metadata is only visible to users with access to this run." => {
            "你可以查看此共享会话，但运行元数据仅对有权访问此运行的用户可见。"
        },
        "A new version of the Warp plugin is available" => "Warp 插件有新版本可用",
        "Expand" => "展开",
        "Hand off to cloud (or type &)" => "交给云端（或输入 &）",
        "Install the Warp plugin to enable rich agent notifications within Warp" => {
            "安装 Warp 插件，以在 Warp 中启用丰富的 Agent 通知"
        },
        "Manage API keys" => "管理 API key",
        "Maximize" => "最大化",
        "Open coding agent settings" => "打开 Coding Agent 设置",
        "Open file" => "打开文件",
        "Open file explorer" => "打开文件资源管理器",
        "Open in GitHub" => "在 GitHub 中打开",
        "Open Rich Input" => "打开富文本输入",
        "Open this conversation in the Warp desktop app" => {
            "在 Warp 桌面应用中打开此对话"
        },
        "Rewind to before this block" => "回退到此块之前",
        "Show version history" => "显示版本历史",
        "Slash commands" => "斜杠命令",
        "This conversation cannot be deleted" => "无法删除此对话",
        "Toggle Case Sensitivity" => "切换大小写敏感",
        "Toggle Regex" => "切换正则",
        "View agent tasks you created" => "查看你创建的 Agent 任务",
        "View instructions to install the Warp plugin" => "查看安装 Warp 插件的说明",
        "View instructions to update the Warp plugin" => "查看更新 Warp 插件的说明",
        "View this run in the Oz web app" => "在 Oz 网页应用中查看此运行",
        "View your agent tasks plus all shared team tasks" => {
            "查看你的 Agent 任务以及所有共享团队任务"
        },
        "Zoom" => "缩放",
        "Add your own custom keybindings to existing actions below." => {
            "在下方为现有操作添加自定义快捷键。"
        },
        "Adds an IDE-style project explorer / file tree to the left side tools panel." => {
            "在左侧工具面板中添加 IDE 风格的项目资源管理器 / 文件树。"
        },
        "Adds global file search to the left side tools panel." => {
            "在左侧工具面板中添加全局文件搜索。"
        },
        "Adjusts the default zoom level across all windows" => {
            "调整所有窗口的默认缩放级别"
        },
        "Agent font" => "Agent 字体",
        "Always" => "始终",
        "Always show tab bar" => "始终显示标签栏",
        "Automatically switch between light and dark themes when your system does." => {
            "当系统切换浅色/深色模式时自动切换主题。"
        },
        "Available" => "可用",
        "Available for download" => "可下载",
        "Auto open code review panel" => "自动打开代码审查面板",
        "Bar" => "竖线",
        "Blinking cursor" => "光标闪烁",
        "Block" => "块状",
        "Blocks" => "块",
        "Busy" => "忙碌",
        "Changing the app icon requires the app to be bundled." => {
            "更改应用图标需要应用已打包。"
        },
        "Checking..." => "正在检查...",
        "Choose a layout to open files in Warp" => "选择在 Warp 中打开文件的布局",
        "Choose an editor to open file links" => "选择用于打开文件链接的编辑器",
        "Choose an editor to open files from the code review panel, project explorer, and global search" => {
            "选择用于打开代码审查面板、项目资源管理器和全局搜索中文件的编辑器"
        },
        "Classic 1" => "经典 1",
        "Classic 2" => "经典 2",
        "Classic 3" => "经典 3",
        "Clear" => "清除",
        "Code Editor and Review" => "代码编辑器与审查",
        "Codebase indexing" => "代码库索引",
        "Codebase Indexing" => "代码库索引",
        "Codebase too large" => "代码库过大",
        "Columns" => "列",
        "Compact mode" => "紧凑模式",
        "Configure keyboard shortcuts" => "配置键盘快捷键",
        "Copyright 2026 Warp" => "Copyright 2026 Warp",
        "Create your own custom theme" => "创建自己的自定义主题",
        "Current theme" => "当前主题",
        "Cursor" => "光标",
        "Cursor type" => "光标类型",
        "Cursor type is disabled in Vim mode" => "Vim 模式下无法设置光标类型",
        "Customize your app icon" => "自定义应用图标",
        "Dark" => "深色",
        "Default" => "默认",
        "Default (no color)" => "默认（无颜色）",
        "Default App" => "默认应用",
        "Dim inactive panes" => "调暗非活动窗格",
        "Disabled" => "已禁用",
        "Discovered" => "已发现",
        "Editor and Code Review" => "编辑器与代码审查",
        "Enforce minimum contrast" => "强制最低对比度",
        "Failed" => "失败",
        "Fix with Oz" => "用 Oz 修复",
        "Focus follows mouse" => "焦点跟随鼠标",
        "Font size (px)" => "字体大小 (px)",
        "Font weight" => "字体粗细",
        "Full-screen Apps" => "全屏应用",
        "Global file search" => "全局文件搜索",
        "Glass Sky" => "玻璃天空",
        "Glow" => "光晕",
        "Group files into single editor pane" => "将文件合并到单个编辑器窗格",
        "Header toolbar layout" => "顶部工具栏布局",
        "Hide code review button in tab bar" => "在标签栏中隐藏代码审查按钮",
        "Hide search bar in vertical tab layout" => "在垂直标签布局中隐藏搜索栏",
        "Hide tab bar if fullscreen" => "全屏时隐藏标签栏",
        "Icon" => "图标",
        "Index limit reached" => "已达到索引数量上限",
        "Index new folders by default" => "默认索引新文件夹",
        "Indexing..." => "正在索引...",
        "Initialization Settings" => "初始化设置",
        "Initialized / indexed folders" => "已初始化 / 已索引文件夹",
        "Input" => "输入",
        "Input position" => "输入位置",
        "Input type" => "输入类型",
        "Keyboard shortcuts are not synced to the cloud" => "键盘快捷键不会同步到云端",
        "Left" => "左侧",
        "Ligatures may reduce performance" => "连字可能会降低性能",
        "Light" => "浅色",
        "Line height" => "行高",
        "LSP SERVERS" => "LSP 服务器",
        "Match terminal" => "匹配终端",
        "Never" => "从不",
        "No folders have been initialized yet." => "尚未初始化任何文件夹。",
        "No index built" => "尚未构建索引",
        "No index created" => "尚未创建索引",
        "Not running" => "未运行",
        "Notebook font size" => "Notebook 字体大小",
        "On high-DPI displays" => "在高 DPI 显示器上",
        "On low-DPI displays" => "在低 DPI 显示器上",
        "Only for named colors" => "仅用于命名颜色",
        "Only on hover" => "仅悬停时",
        "Only show tab bar on hover" => "仅悬停时显示标签栏",
        "Open Markdown files in Warp's Markdown Viewer by default" => {
            "默认使用 Warp 的 Markdown 查看器打开 Markdown 文件"
        },
        "Open new windows with custom size" => "新窗口使用自定义大小",
        "Open project rules" => "打开项目规则",
        "Panes" => "窗格",
        "Pin Input to the Bottom" => "将输入框固定到底部",
        "Pin Input to the Top" => "将输入框固定到顶部",
        "Pin to the bottom (Warp mode)" => "固定到底部（Warp 模式）",
        "Pin to the top (Reverse mode)" => "固定到顶部（反向模式）",
        "Preserve active tab color for new tabs" => "新标签页保留当前活动标签颜色",
        "Project explorer" => "项目资源管理器",
        "Reset to default" => "重置为默认值",
        "Right" => "右侧",
        "Rows" => "行",
        "Shell (PS1)" => "Shell (PS1)",
        "Show a button in the top right of the window to toggle the code review panel." => {
            "在窗口右上角显示用于切换代码审查面板的按钮。"
        },
        "Show block dividers" => "显示块分隔线",
        "Show code review button" => "显示代码审查按钮",
        "Show code review button in tab bar" => "在标签栏中显示代码审查按钮",
        "Show diff stats on code review button" => "在代码审查按钮上显示差异统计",
        "Show Jump to Bottom of Block button" => "显示跳转到块底部按钮",
        "Show ligatures in terminal" => "在终端中显示连字",
        "Show lines added and removed counts on the code review button." => {
            "在代码审查按钮上显示新增和删除行数。"
        },
        "Show tab indicators" => "显示标签页指示器",
        "Show the latest user prompt instead of the generated conversation title for Oz and third-party agent sessions in vertical tabs." => {
            "在垂直标签页中，对 Oz 和第三方 Agent 会话显示最新用户提示，而不是生成的对话标题。"
        },
        "Show the tab bar" => "显示标签栏",
        "Show vertical tabs panel in restored windows" => "在恢复的窗口中显示垂直标签面板",
        "Split Pane" => "拆分窗格",
        "Stale" => "已过期",
        "Start Input at the Top" => "从顶部开始输入",
        "Start at the top (Classic mode)" => "从顶部开始（经典模式）",
        "Stopped" => "已停止",
        "Sync with OS" => "跟随系统",
        "Syncing..." => "正在同步...",
        "Tab close button position" => "标签关闭按钮位置",
        "Tabs" => "标签页",
        "Terminal font" => "终端字体",
        "The selected graphics settings may not support rendering transparent windows." => {
            "所选图形设置可能不支持渲染透明窗口。"
        },
        "The selected hardware may not support rendering transparent windows." => {
            "所选硬件可能不支持渲染透明窗口。"
        },
        "Themes" => "主题",
        "This setting is not synced to your other devices" => "此设置不会同步到你的其他设备",
        "This shortcut conflicts with other keybinds" => "此快捷键与其他快捷键冲突",
        "Toggle Input Mode (Warp/Classic)" => "切换输入模式（Warp/Classic）",
        "to reference these keybindings in a side pane at anytime." => {
            "随时在侧边窗格中查看这些快捷键。"
        },
        "Tools panel visibility is consistent across tabs" => "工具面板可见性在标签页之间保持一致",
        "Transparency is not supported with your graphics drivers." => {
            "你的图形驱动不支持透明效果。"
        },
        "Underline" => "下划线",
        "Unavailable" => "不可用",
        "Use" => "使用",
        "Use custom padding in alt-screen" => "在 alt-screen 中使用自定义内边距",
        "Use latest user prompt as conversation title in tab names" => {
            "在标签名称中使用最新用户提示作为对话标题"
        },
        "Use thin strokes" => "使用细笔画",
        "Use vertical tab layout" => "使用垂直标签布局",
        "Use Window Blur (Acrylic texture)" => "使用窗口模糊（亚克力纹理）",
        "View all available system fonts" => "查看所有可用系统字体",
        "View logs" => "查看日志",
        "AI Features must be enabled to use codebase indexing." => {
            "必须启用 AI 功能才能使用代码库索引。"
        },
        "Team admins have disabled codebase indexing." => "团队管理员已禁用代码库索引。",
        "Team admins have enabled codebase indexing." => "团队管理员已启用代码库索引。",
        "To exclude specific files or directories from indexing, add them to the .warpindexingignore file in your repository directory. These files will still be accessible to AI features, but they won't be included in codebase embeddings." => {
            "要从索引中排除特定文件或目录，请将它们添加到仓库目录中的 .warpindexingignore 文件。这些文件仍可供 AI 功能访问，但不会包含在代码库嵌入中。"
        },
        "Warp can automatically index code repositories as you navigate them, helping agents quickly understand context and provide solutions. Code is never stored on the server. If a codebase is unable to be indexed, Warp can still navigate your codebase and gain insights via grep and find tool calling." => {
            "Warp 可以在你浏览代码仓库时自动建立索引，帮助 Agent 快速理解上下文并提供解决方案。代码绝不会存储在服务器上。如果某个代码库无法建立索引，Warp 仍可通过 grep 和 find 工具调用浏览代码库并获取信息。"
        },
        "When enabled, reopening or restoring a window opens the vertical tabs panel even if it was closed when the window was last saved." => {
            "启用后，重新打开或恢复窗口时，即使上次保存窗口时垂直标签面板已关闭，也会打开它。"
        },
        "When set to true, Warp will automatically index code repositories as you navigate them - helping agents quickly understand context and provide targeted solutions." => {
            "设为 true 时，Warp 会在你浏览代码仓库时自动建立索引，帮助 Agent 快速理解上下文并提供有针对性的解决方案。"
        },
        "When this setting is on, any files opened in the same tab will be automatically grouped into a single editor pane." => {
            "启用后，在同一标签页中打开的文件会自动合并到单个编辑器窗格。"
        },
        "When this setting is on, the code review panel will open on the first accepted diff of a conversation" => {
            "启用后，代码审查面板会在对话中首次接受差异时打开"
        },
        "When using the vertical tab layout, hide the search bar in the title bar. Search stays available via the command palette and keyboard shortcuts." => {
            "使用垂直标签布局时，隐藏标题栏中的搜索栏。仍可通过命令面板和键盘快捷键进行搜索。"
        },
        "When windowed" => "窗口模式时",
        "Window Blur Radius:" => "窗口模糊半径：",
        "Window Blur Radius: " => "窗口模糊半径：",
        "Window Opacity:" => "窗口不透明度：",
        "Window Opacity: " => "窗口不透明度：",
        "You have reached the maximum number of codebase indices for your plan. Delete existing indices to auto-index new codebases." => {
            "你已达到当前套餐允许的代码库索引数量上限。请删除现有索引后再自动索引新的代码库。"
        },
        "You may need to restart Warp for MacOS to apply the preferred icon style." => {
            "你可能需要重启 Warp for MacOS 才能应用首选图标样式。"
        },
        _ => return None,
    })
}
